// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class Contract
{
    public int Id { get; set; }

    public int? PartnerId { get; set; }

    public string ContractNumber { get; set; }

    public DateOnly? ContractDate { get; set; }

    public decimal? TotalValue { get; set; }

    public string PaymentTerms { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<ContractDetailMovie> ContractDetailMovies { get; set; } = new List<ContractDetailMovie>();

    public virtual ICollection<ContractFile> ContractFiles { get; set; } = new List<ContractFile>();

    public virtual Partner Partner { get; set; }
}