// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace dbMovies.Models;

public partial class dbMoviesContext : DbContext
{
    public dbMoviesContext(DbContextOptions<dbMoviesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<ContractDetailMovie> ContractDetailMovies { get; set; }

    public virtual DbSet<ContractFile> ContractFiles { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<FavoriteMovie> FavoriteMovies { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }

    public virtual DbSet<Movie> Movies { get; set; }

    public virtual DbSet<MovieFile> MovieFiles { get; set; }

    public virtual DbSet<MoviePriceHistory> MoviePriceHistorys { get; set; }

    public virtual DbSet<MoviePricing> MoviePricings { get; set; }

    public virtual DbSet<Partner> Partners { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleUser> RoleUsers { get; set; }

    public virtual DbSet<SubscriptionPackage> SubscriptionPackages { get; set; }

    public virtual DbSet<UserCustomer> UserCustomers { get; set; }

    public virtual DbSet<UserEmployee> UserEmployees { get; set; }

    public virtual DbSet<WatchHistory> WatchHistories { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC07BC765BC5");

            entity.Property(e => e.CategoryName).HasMaxLength(100);
            entity.Property(e => e.Color).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contract__3214EC07A18760D6");

            entity.HasIndex(e => e.ContractNumber, "UQ__Contract__C51D43DA97529F95").IsUnique();

            entity.Property(e => e.ContractNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.PartnerId).HasColumnName("PartnerID");
            entity.Property(e => e.TotalValue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Partner).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.PartnerId)
                .HasConstraintName("FK_Contract_Partner");
        });

        modelBuilder.Entity<ContractDetailMovie>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contract__3214EC075EB1184A");

            entity.Property(e => e.ContractId).HasColumnName("ContractID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Contract).WithMany(p => p.ContractDetailMovies)
                .HasForeignKey(d => d.ContractId)
                .HasConstraintName("FK_ContractDetailMovie_Contract");

            entity.HasOne(d => d.Movie).WithMany(p => p.ContractDetailMovies)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK_ContractDetailMovie_Movie");
        });

        modelBuilder.Entity<ContractFile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contract__3214EC07BC390A2E");

            entity.Property(e => e.ContractId).HasColumnName("ContractID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FileName).HasMaxLength(255);
            entity.Property(e => e.FilePath).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.UploadDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Contract).WithMany(p => p.ContractFiles)
                .HasForeignKey(d => d.ContractId)
                .HasConstraintName("FK_ContractFile_Contract");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Customer__3214EC0740942A13");

            entity.Property(e => e.Address).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07F9F992E3");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(500);
            entity.Property(e => e.JobStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Salary).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<FavoriteMovie>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Favorite__3214EC070BEF2E17");

            entity.Property(e => e.AddedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.MovieId).HasColumnName("MovieID");

            entity.HasOne(d => d.Customer).WithMany(p => p.FavoriteMovies)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_FavoriteMovies_Customer");

            entity.HasOne(d => d.Movie).WithMany(p => p.FavoriteMovies)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK_FavoriteMovies_Movies");
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Invoices__3214EC0770519FD3");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.InvoiceDate).HasColumnType("datetime");
            entity.Property(e => e.InvoiceNumber).HasMaxLength(50);
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.PaymentStatus).HasMaxLength(20);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Customer).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Invoices_UserCustomer");
        });

        modelBuilder.Entity<InvoiceDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__InvoiceD__3214EC07C3D3B87B");

            entity.Property(e => e.AccessEnd).HasColumnType("datetime");
            entity.Property(e => e.AccessStart).HasColumnType("datetime");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.PackageEnd).HasColumnType("datetime");
            entity.Property(e => e.PackageStart).HasColumnType("datetime");
            entity.Property(e => e.PricingType).HasMaxLength(50);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Invoice).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.InvoiceId)
                .HasConstraintName("FK_InvoiceDetails_Invoices");

            entity.HasOne(d => d.Movie).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK_InvoiceDetails_Movies");

            entity.HasOne(d => d.Package).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.PackageId)
                .HasConstraintName("FK_InvoiceDetails_SubscriptionPackage");
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Movies__3214EC07AA4777CF");

            entity.Property(e => e.AgeLimit).HasMaxLength(10);
            entity.Property(e => e.BoxOffice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Budget).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Country).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Director).HasMaxLength(255);
            entity.Property(e => e.LanguageList).HasMaxLength(255);
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 1)");
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.Title).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Category).WithMany(p => p.Movies)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Movies_Categories");
        });

        modelBuilder.Entity<MovieFile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MovieFil__3214EC073C93638D");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FileName).HasMaxLength(255);
            entity.Property(e => e.FilePath).HasMaxLength(500);
            entity.Property(e => e.FileType).HasMaxLength(20);
            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Movie).WithMany(p => p.MovieFiles)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK_MovieFile_Movies");
        });

        modelBuilder.Entity<MoviePriceHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MoviePri__3214EC0766735609");

            entity.Property(e => e.ChangedDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.NewPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OldPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PricingType).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Movie).WithMany(p => p.MoviePriceHistories)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK_MoviePriceHistory_Movies");
        });

        modelBuilder.Entity<MoviePricing>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MoviePri__3214EC070B230405");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PricingType).HasMaxLength(50);
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Movie).WithMany(p => p.MoviePricings)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK_MoviePricing_Movies");
        });

        modelBuilder.Entity<Partner>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Partner__39FD63327971F201");

            entity.Property(e => e.AccountNumber).HasMaxLength(50);
            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.BankName).HasMaxLength(255);
            entity.Property(e => e.ContactInfo).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Active");
            entity.Property(e => e.TaxCode).HasMaxLength(50);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Website).HasMaxLength(255);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC079C3BB957");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<RoleUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoleUser__3214EC071CDADCBB");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleUsers)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_RoleUsers_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.RoleUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_RoleUsers_Users");
        });

        modelBuilder.Entity<SubscriptionPackage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Subscrip__3214EC07BC2C919B");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserCustomer>(entity =>
        {
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.PasswordHash).HasMaxLength(256);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Customer).WithMany(p => p.UserCustomers)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_UserCustomer_Customer");
        });

        modelBuilder.Entity<UserEmployee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserEmpl__3214EC07F5E76BE6");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.PasswordHash).HasMaxLength(256);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Employee).WithMany(p => p.UserEmployees)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK_UserEmployees_Employees");
        });

        modelBuilder.Entity<WatchHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WatchHis__3214EC078FD13012");

            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.LastPosition).HasDefaultValue(0);
            entity.Property(e => e.LastWatched).HasColumnType("datetime");
            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.WatchStatus).HasMaxLength(20);

            entity.HasOne(d => d.Customer).WithMany(p => p.WatchHistories)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_WatchHistory_Customer");

            entity.HasOne(d => d.Movie).WithMany(p => p.WatchHistories)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK_WatchHistory_Movies");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}