// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public bool? Gender { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string JobStatus { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public decimal? Salary { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<UserEmployee> UserEmployees { get; set; } = new List<UserEmployee>();
}