// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class FavoriteMovie
{
    public int Id { get; set; }

    public int? CustomerId { get; set; }

    public int? MovieId { get; set; }

    public DateTime? AddedDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Movie Movie { get; set; }
}