// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class InvoiceDetail
{
    public int Id { get; set; }

    public int? InvoiceId { get; set; }

    public int? MovieId { get; set; }

    public int? PackageId { get; set; }

    public string PricingType { get; set; }

    public decimal? UnitPrice { get; set; }

    public DateTime? AccessStart { get; set; }

    public DateTime? AccessEnd { get; set; }

    public DateTime? PackageStart { get; set; }

    public DateTime? PackageEnd { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdateBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual SubscriptionPackage Package { get; set; }
}