// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class Movie
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int? CategoryId { get; set; }

    public string Description { get; set; }

    public string Director { get; set; }

    public string Cast { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public string LanguageList { get; set; }

    public string Country { get; set; }

    public string AgeLimit { get; set; }

    public decimal? Rating { get; set; }

    public decimal? Budget { get; set; }

    public decimal? BoxOffice { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ContractDetailMovie> ContractDetailMovies { get; set; } = new List<ContractDetailMovie>();

    public virtual ICollection<FavoriteMovie> FavoriteMovies { get; set; } = new List<FavoriteMovie>();

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    public virtual ICollection<MovieFile> MovieFiles { get; set; } = new List<MovieFile>();

    public virtual ICollection<MoviePriceHistory> MoviePriceHistories { get; set; } = new List<MoviePriceHistory>();

    public virtual ICollection<MoviePricing> MoviePricings { get; set; } = new List<MoviePricing>();

    public virtual ICollection<WatchHistory> WatchHistories { get; set; } = new List<WatchHistory>();
}