// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class MoviePriceHistory
{
    public int Id { get; set; }

    public int? MovieId { get; set; }

    public string PricingType { get; set; }

    public decimal? OldPrice { get; set; }

    public decimal? NewPrice { get; set; }

    public int? RentalDurationDays { get; set; }

    public DateTime? ChangedDate { get; set; }

    public int? ChangedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Movie Movie { get; set; }
}