// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class MovieFile
{
    public int Id { get; set; }

    public int? MovieId { get; set; }

    public string FileType { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public DateTime? UploadDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Movie Movie { get; set; }
}