// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class Partner
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ContactInfo { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Website { get; set; }

    public string TaxCode { get; set; }

    public string AccountNumber { get; set; }

    public string BankName { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();
}