// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbMovies.Models;

public partial class WatchHistory
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? MovieId { get; set; }

    public decimal? CurrentTime { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual UserCustomer User { get; set; }
}